### ISSUE TITLE
Should the "The linker bottleneck" seciton mention mold?

### ISSUE THREAD

**Issue by FRex** [fabiensanglard/dc#10]
Mold is a new super-fast linker by one of LLVM/ldd main developers that utilizes all the available cores and aims to be as fast as copying the file with cat, without need for incremental linking: https://github.com/rui314/mold

Would it make sense to also mention it in the "The linker bottleneck" section at https://fabiensanglard.net/dc/driver.php  and in the linker page itself at https://fabiensanglard.net/dc/ld.php ?

**Comment by fabiensanglard** [comment]
Fixed in 2b04a473b4a0e9bb60b2a2a1d9652c7c888f63ec
