### ISSUE TITLE
Source filename consistency

### ISSUE THREAD

**Issue by denilsonsa** [fabiensanglard/dc#17]
At `driver.php`, section *Driving a multi-file project*, we have a command-line example compiling three `.c` files. However, the diagram just below it shows one `.c`, one `.cpp` and one `.m` source files. Some consistency in the examples would be better.

I'd suggest it myself (through a PR), but I have no experience compiling stuff in clang, so I don't know if the command-lines need to be different for the other languages.

![image](https://github.com/fabiensanglard/dc/assets/121676/843bfaf5-e721-4590-b32b-915da750b284)

**Comment by fabiensanglard** [comment]
Changing the filenames seems to be the correct fix. Feel free to send a PR.
