### ISSUE TITLE
engine.cc includes engine.h three times, not two

### ISSUE THREAD

**Issue by denilsonsa** [fabiensanglard/dc#20]
In `cpp.php`, section *Header guards*, we have `engine.cc` including all three header files: `engine.h`, `render.h` and `ai.h`. But the last two header files also include `engine.h`. This means this base header is included THREE times, not two.

Thus, we have a lot of things to fix:

* [x] The output from `clang`, the error message should be different.
* [x] The TU from engine.cc, the `struct World` should be listed three times.
* [x] The paragraph text, as the paragraph assumes it's included two times instead of three.

Alternatively, a smaller solution is to:

* [ ] Remove `#include "engine.h"` from `engine.cc`
* [ ] Slightly fix the paragraph text.

**Comment by fabiensanglard** [comment]
Fixed 2/ and 3/ in 7b07eea94073d34685a6f567ec64fd0e4d40e084.

1/ Needs no fixing. clang only output additional include after the first one so two is correct.
